export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const POST_LOGIN = 'POST_LOGIN';

export const DID_LOGIN_ACTION = 'DID_LOGIN_ACTION';



export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';


export const LAY_DANH_SACH_DON_HANG = 'LAY_DANH_SACH_DON_HANG'
export const LAY_DANH_SACH_DON_HANG_THANH_CONG = 'LAY_DANH_SACH_DON_HANG_THANH_CONG'
export const LAY_DANH_SACH_DON_HANG_THAT_BAI = 'LAY_DANH_SACH_DON_HANG_THAT_BAI'
